#!/bin/bash
#
# statsdaemon - start and stop 
# https://github.com/wojtekzw/statsdaemon
#

### BEGIN INIT INFO
# Provides:          statsdaemon statsd
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Should-Start:      $network $named $syslog $time
# Should-Stop:       $network $named $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start the statsdaemon
### END INIT INFO

set -e

PATH=/sbin:/bin:/usr/sbin:/usr/bin

NAME=statsdaemon

DAEMON=/usr/bin/${NAME}
PIDFILE=/var/run/${NAME}.pid
CONFIGFILE=/etc/statsdaemon/statsdaemon.yml

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

if [ -r /etc/default/${NAME} ]; then
    . /etc/default/${NAME}
fi
if [ ! -r ${CONFIGFILE} ]; then
    echo "${CONFIGFILE} does not exist"
	exit -1
fi

case "$1" in
    start)
        echo -n "Starting $DESC: $NAME"
        start-stop-daemon --start --quiet --oknodo \
      	   --pidfile "$PIDFILE" --make-pidfile \
           --background \
           --exec $DAEMON -- --config=$CONFIGFILE
        echo "."
        ;;
    stop)
        echo -n "Stopping $DESC: $NAME"
        PID=$( cat "$PIDFILE" 2> /dev/null ) || true
        start-stop-daemon --stop --quiet --oknodo --pidfile "$PIDFILE"
        echo "."
		# FIXME
	    rm -f "${PIDFILE}" 
        ;;
    status)
        PID=$( cat "$PIDFILE" 2> /dev/null ) || true
        if test -n "$PID" && kill -0 $PID 2> /dev/null; then
            echo "${NAME} ($PID) is running."
            exit 0
        else
            PID=$( pidof ${NAME} ) || true

            if test -n "$PID"; then
                echo "${NAME} ($PID) is running."
                exit 0
            else
                echo "${NAME} is stopped."
            fi
        fi
        ;;
    restart|force-reload)
        echo -n "Restarting $DESC: $NAME"
        $0 stop
        sleep 1
        $0 start
        echo "."
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|force-reload|status}" >&2
        exit 1
        ;;
esac

exit 0

# vim: syntax=sh noexpandtab sw=4 ts=4 :
